name: sqflite_example_android
description: Demonstrates how to use the sqflite plugin and perform some tests.
publish_to: none
version: '0.4.0'

environment:
  sdk: ^3.9.0

dependencies:
  path: any
  collection: any
  flutter:
    sdk: flutter
  sqflite_android:
  sqflite_common:
  synchronized:
  matcher:
  meta:
  sqflite_example_common:
    git:
      url: https://github.com/tekartik/sqflite
      path: packages_flutter/sqflite_example_common
dev_dependencies:
  flutter_lints: ">=5.0.0"
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test:
  process_run: '>=1.2.0'
  pub_semver: 

dependency_overrides:
  sqflite_android:
    path: ../
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true


