name: sqflite_platform_interface
repository: https://github.com/tekartik/sqflite/tree/master/sqflite_platform_interface
issue_tracker: https://github.com/tekartik/sqflite/issues
description: Flutter plugin interface for SQLite, a self-contained, high-reliability,
  embedded, SQL database engine.
version: 2.4.0

environment:
  sdk: ^3.9.0
  flutter: ">=3.24.0"

topics:
  - sql
  - database

dependencies:
  flutter:
    sdk: flutter
  platform: ">=3.0.0 <5.0.0"
  sqflite_common: ">=2.5.4+5 <4.0.0"
  plugin_platform_interface: ">=2.1.7 <4.0.0"
  meta: ">=1.15.0 <3.0.0"

dev_dependencies:
  flutter_lints: ">=5.0.0"
  flutter_test:
    sdk: flutter
  test_api: '>=0.2.19'
  pub_semver: '>=2.0.0'
